Feature/summary socorros data
IslasGECI/datatools pull request #1
Opened 2020-05-11 18:23 UTC by MaritzaB

Agrega función `separa_estaciones_por_isla` para separar la tabla de estaciones climaticas IG por estación y por año.

2020-05-11 18:41 UTC, devarops requested changes
Buen trabajo.
Aquí te dejo mi revisión.

2020-05-11 18:41 UTC, evaristor commented on src/separa_estaciones_por_isla
> +    Date LIKE '%${year}'
Incrementa la indentación del _query_  que se encuentra entre `"`

2020-05-11 18:41 UTC, evaristor commented on Dockerfile
> +RUN pip install csvkit
Agrega fín de línea en la última línea

2020-05-11 18:41 UTC, evaristor commented on Dockerfile
> +FROM islasgeci/base:89e5
¿No funciona con la versión más nueva `82ce`?

2020-05-11 18:41 UTC, evaristor commented on Makefile
> +	export PATH="$${PATH}:/usr/local/bin"
Agrega fín de línea en la última línea

2020-05-11 18:41 UTC, evaristor commented on src/resumen_semanal
> +rm resumen_semanal.csv
Agrega fín de línea en la última línea

2020-05-11 18:41 UTC, evaristor commented on src/separa_estaciones_por_isla
> +done
Agrega fín de línea en la última línea

2020-05-11 18:41 UTC, evaristor commented on src/transpon_esfuerzo_captura
> +tr --squeeze-repeats '\n' "," | cut --fields=-2 --delimiter=,
Agrega fín de línea en la última línea

2020-05-14 16:24 UTC, devarops requested changes
¿Este _pr_ se encuentra asociada a alguna tarea en el pizarrón?
Si sí, a cuál? ¿En cuál renglón se encuentra o qué estamos revisando?

2020-05-14 16:24 UTC, evaristor commented on Makefile
> +
Elimina el _tab_ de la línea 16.

2020-05-14 16:24 UTC, evaristor commented on src/resumen_semanal
> +rm resumen_semanal.csv
Agrega fín de línea en la última línea

2020-05-14 16:38 UTC, MaritzaB commented
> ¿Este _pr_ se encuentra asociada a alguna tarea en el pizarrón?
> Si sí, a cuál? ¿En cuál renglón se encuentra o qué estamos revisando?

Si, el _PR_ está asociado a [esta tarea](https://app.gitkraken.com/glo/view/card/1bb8108f6a4849e2af8c31ac462def71) que está en el renglón de implementación.
Lo que estamos revisando es es el script de `separa_estaciones_por_isla`.
Lo que pasa es que la regué x_x porque consigné en una rama abierta por que en esa rama estaba el Dockerfile y el Makefile y esos archivos. Entonces si abría otra pensé que tendría algunos problemas... -_- Por eso hay otros scripts pero todos esos fueron checados con Nepo.

2020-05-15 16:12 UTC, devarops requested changes
Aquí están mis comentarios.

2020-05-15 16:12 UTC, evaristor commented on src/separate_by_station_and_year
> +./remove_empty_files
Agraga fin de línea a la última línea

2020-05-15 16:12 UTC, evaristor commented on Makefile
> +	if [ ! -d /usr/local/bin ]; then mkdir /usr/local/bin; fi
```suggestion
	mkdir --parents /usr/local/bin
```

2020-05-15 16:12 UTC, evaristor commented on src/cuenta_gatos
> +#Cuenta las noches trampas activas (A) y las capturas de gatos (X)
```suggestion
# Cuenta las noches trampas activas (A) y las capturas de gatos (X)
```

2020-05-15 16:12 UTC, evaristor commented on src/remove_empty_files
> +#
Agrega conmentario describiendo que hace este _script_

2020-05-15 16:12 UTC, evaristor commented on src/resumen_semanal
> +#Cuenta gatos semanalmente del registro posicion trampas de Socorro
```suggestion
# Cuenta gatos semanalmente del registro posicion trampas de Socorro
```

2020-05-15 16:12 UTC, evaristor commented on src/separate_by_station_and_year
> +#Función que separa la tabla de estaciones meteorológicas de IG por estación y por año
```suggestion
# Función que separa la tabla de estaciones meteorológicas de IG por estación y por año
```

2020-05-15 16:12 UTC, evaristor commented on src/transpon_esfuerzo_captura
> +#Transpone los resultados de `cuenta_gatos.sh`
```suggestion
# Transpone los resultados de `cuenta_gatos.sh`
```

2020-05-15 17:52 UTC, devarops requested changes
Aquí te dejo mis comentarios.

2020-05-15 17:52 UTC, evaristor commented on Dockerfile
> +RUN pip install csvkit
Creo que esto ya está en [la base](https://github.com/IslasGECI/docker/blob/develop/_Dockerfile.body#L13) que estás usando. Tal vez aquí ya no la necesitas.

2020-05-15 17:52 UTC, evaristor commented on src/resumen_semanal
> +#Cuenta el total de noches trampa y el total de capturas
```suggestion

# Cuenta el total de noches trampa y el total de capturas
```

2020-05-15 18:26 UTC, devarops requested changes
Aquí te dejo mis comentarios

2020-05-15 18:26 UTC, evaristor commented on src/cuenta_gatos
> +archivo_de_entrada=${1}
En este script las variables se encuentran en español. En otros scripts se encuentran en inglés. Por favor pon las variables en el mismo idioma.

2020-05-15 18:26 UTC, evaristor commented on src/remove_empty_files
> +file_list=$(ls *.csv)
En este script las variables se encuentran en ingles. En otros scripts se encuentran en español. Por favor pon las variables en el mismo idioma.

2020-05-15 18:26 UTC, evaristor commented on src/resumen_semanal
> +lista_archivos=$(ls *.csv)
En este script las variables se encuentran en español. En otros scripts se encuentran en inglés. Por favor pon las variables en el mismo idioma.

2020-05-15 18:26 UTC, evaristor commented on src/separate_by_station_and_year
> +for station in Norte Pista Sur Bosque; do
En este script las variables se encuentran en ingles. En otros scripts se encuentran en español. Por favor pon las variables en el mismo idioma.

2020-05-15 18:26 UTC, evaristor commented on src/transpon_esfuerzo_captura
> +# Transpone los resultados de `cuenta_gatos.sh`
```suggestion
# Transpone los resultados de 'cuenta_gatos'
```

2020-05-15 18:26 UTC, evaristor commented on src/transpon_esfuerzo_captura
> +# Transpone los resultados de `cuenta_gatos.sh`
Creo que `cuenta_gatos` ya no tiene la extensión `.sh`

2020-05-15 19:54 UTC, devarops requested changes
Parece que el GitHub Actions [está fracasando](https://github.com/IslasGECI/datatools/runs/679322304).

2020-05-15 19:54 UTC, evaristor commented on Makefile
> +	cd tests && . ./test_geci-tdp2xls
Estas tres líneas hacen referencia a uno archivos `test_*` en el directorio `tests/`, pero no puedo encontrar ese directorio ni los archivos. ¿Sabes donde están?

2020-05-15 20:02 UTC, evaristor commented
@MaritzaB Me parece que copiaste el `Makefile` de **misctools**. Allá tienen sentido estas líneas:

```
	. ./tests/test_geci-install
	. ./tests/test_make-install
	cd tests && . ./test_geci-tdp2xls
```

Sin embargo, aquí no existen estos archivos. Debiste notar eso la momento de hacer `make` dentro del contenedor antes de solicitar revisión.

2020-05-25 18:09 UTC, devarops requested changes
El nombre `separate_by_station_and_year` me parece poco convencional. Te propongo estas alternativas:

- `group_by_station_and_year`
- `aggregate_by_station_and_year`

2020-05-25 19:07 UTC, merged

2020-05-25 19:09 UTC, evaristor commented
@MaritzaB: ¡Buen trabajo!

2020-05-25 19:10 UTC, MaritzaB commented
> @MaritzaB: ¡Buen trabajo!

Woow, muchas gracias @evaristor! :)

2020-05-25 19:11 UTC, evaristor commented
Gracias a ti, @MaritzaB :smile: